=== lybugproducer/lyrpc/lyrpc-core/src/main/resources/dtd/lyrpc-provider.dtd
<!ELEMENT lyrpc-provider (registry | datagram | server)*>

        <!ELEMENT registry (registry-class, registry-url+)>
        <!ELEMENT registry-class (#PCDATA)>
        <!ELEMENT registry-url (#PCDATA)>

        <!ELEMENT datagram (serializer-class, compressor-class)>
        <!ELEMENT serializer-class (#PCDATA)>
        <!ELEMENT compressor-class (#PCDATA)>

        <!ELEMENT server (address, worker-threads)>
        <!ELEMENT address (#PCDATA)>
        <!ELEMENT worker-threads (#PCDATA)>

=== lybugproducer/lyrpc/lyrpc-demo/lyrpc-provider-demo/src/main/resources/lyrpc-provider.xml
<?xml version="1.0" encoding="UTF-8" ?>

<!DOCTYPE lyrpc-provider SYSTEM "lyrpc-provider.dtd">

<lyrpc-provider>

    <registry>
        <registry-class>com.lyrpc.core.discovery.impl.ZookeeperProviderRegistry</registry-class>
        <registry-url>127.0.0.1:2181</registry-url>
    </registry>

    <datagram>
        <serializer-class>com.lyrpc.core.serializer.impl.JdkSerializer</serializer-class>
        <compressor-class>com.lyrpc.core.compressor.impl.GzipCompressor</compressor-class>
    </datagram>

    <server>
        <address>127.0.0.1:23456</address>
        <worker-threads>10</worker-threads>
    </server>

</lyrpc-provider>
